###
# Création livreur
POST http://localhost:4545/admin HTTP/1.1
Content-Type: application/json

{
  "lastname": "test",
  "firstname": "test",
  "email": "aze@mail.com",
  "password": "azerty",
  "phone": 123
}

###
# Récupération des admin
GET http://localhost:4545/admin HTTP/1.1
Content-Type: application/json

###
# Récupération d'un admin
GET http://localhost:4545/admin?id=63ea647abfc21390062c1518 HTTP/1.1
Content-Type: application/json

###
# Modifier un admin
PATCH http://localhost:4545/admin/63e017835d1719e427da79cf HTTP/1.1
Content-Type: application/json

{
  "lastname": "rafiq"
}

###
# Supprimer un admin
DELETE http://localhost:4545/admin/63def78ce599dc07aa81eb5d HTTP/1.1
Content-Type: application/json
