###
# Création client
POST http://localhost:4545/customer HTTP/1.1
Content-Type: application/json

{
  "lastname": "test",
  "firstname": "test",
  "email": "aa@mail.com",
  "password": "azerty",
  "phone": "012345789",
  "langage": "FR"
}

###
# Récupération des client
GET http://localhost:4545/customer HTTP/1.1
Content-Type: application/json

###
# Récupération d'un client
GET http://localhost:4545/customer?id=63e2390a6fbf120931a73a53 HTTP/1.1
Content-Type: application/json

###
# Modifier un client
PATCH http://localhost:4545/customer/63e2390a6fbf120931a73a53 HTTP/1.1
Content-Type: application/json

{
  "lastname": "rafiq"
}

###
# Supprimer un client
DELETE http://localhost:4545/customer/63e2390a6fbf120931a73a53 HTTP/1.1
Content-Type: application/json
