###
# Création livreur
POST http://localhost:4500/deliverer HTTP/1.1
Content-Type: application/json

{
    "lastname": "test",
    "firstname": "test",
    "email": "test@gmail.com",
    "password": "azerty",
    "phone": 123,
    "langage": "FR"
}

###
# Récupération des livreurs
GET http://localhost:4500/deliverer HTTP/1.1
Content-Type: application/json
