###
# Créer un colis
POST http://localhost:4500/parcel HTTP/1.1
Content-Type: application/json

{
  "address_expedition": "123 Main Street, Anytown USA",
  "address_delivery": "456 Elm Street, Anytown USA",
  "weight": "12kg",
  "width": "15cm",
  "length": "20cm",
  "height": "12cm",
  "fragile": "true",
  "emergency": "false"
}

###
# Récupération des colis
GET http://localhost:4500/parcel HTTP/1.1
Content-Type: application/json

###
# Récupération un colis
GET http://localhost:4500/parcel?tracking_id=fae5b266-374e-498f-a609-4b655ec55c40 HTTP/1.1
Content-Type: application/json

###
# Modifier un colis
PUT http://localhost:4500/parcel HTTP/1.1
Content-Type: application/json

{
  "tracking_id": "790a3795-3a29-4757-944f-2cfc5d189790",
  "weight": "33332kg",
  "height": "666dsdsd712cm"
}


###
# Supprimer un livreur
DELETE http://localhost:4500/parcel HTTP/1.1
Content-Type: application/json

{
  "tracking_id": "790a3795-3a29-4757-944f-2cfc5d189790"
}
