###
# Créer un colis
POST http://localhost:4545/parcel HTTP/1.1
Content-Type: application/json

{
  "address_expedition": "123 Main Street, Anytown USA",
  "address_delivery": "456 Elm Street, Anytown USA",
  "weight": 12,
  "width": 15,
  "length": 20,
  "height": 12,
  "is_fragile": true,
  "is_emergency": false,
  "delivery_date": "false",
  "price": 120,
  "customerid": "63ea874444f6bc17dd01938e"
}

###
# Récupération des colis
GET http://localhost:4545/parcel HTTP/1.1
Content-Type: application/json

###
# Récupération d'un colis avec l'id
GET http://localhost:4545/parcel?id=63e24eb9059c0066b55bb4f0 HTTP/1.1
Content-Type: application/json

###
# Récupération d'un colis avec le trackingid
GET http://localhost:4545/parcel?trackingid=ee5d1dbb-122a-4495-b855-b9ddbfd851 HTTP/1.1
Content-Type: application/json

###
# Modifier un colis
PATCH http://localhost:4545/parcel/63e24eb8059c0066b55bb4ed HTTP/1.1
Content-Type: application/json

{
  "trackingid": "648e6cab-be71-4c7a-bb83-a8fa831302b3",
  "weight": "3",
  "height": "666dsdm"
}


###
# Supprimer un colis
DELETE http://localhost:4545/parcel/63e24eb9059c0066b55bb4f0 HTTP/1.1
Content-Type: application/json


###
# Ajout d'une preuve à un colis
PATCH http://localhost:4545/parcel/63e24eb9059c0066b55bb4f0 HTTP/1.1
Content-Type: application/json

{
  "proof_of_delivery": ""
}
