###
# Créer une tournée
POST http://localhost:4545/round HTTP/1.1
Content-Type: application/json

{
  "schedule_date": "13",
  "delivererid": "63ea67f6bfc21390062c153d",
  "parcels": ["63ea882f9e992593fdeb5310"]
}

###
# Créer une tournée sans colis
POST http://localhost:4545/round/empty HTTP/1.1
Content-Type: application/json

{
  "schedule_date": "13",
  "delivererid": "63ea67f6bfc21390062c153d"
}

###
# Récupération des tournées
GET http://localhost:4545/round HTTP/1.1
Content-Type: application/json

###
# Récupération une tournée
GET http://localhost:4545/round?id=63e06513d2851a8bb53f4bb7 HTTP/1.1
Content-Type: application/json

###
# Modifier une tournée
PATCH http://localhost:4545/round/63ea88399e992593fdeb5316  HTTP/1.1
Content-Type: application/json

{
  "schedule_date": "15"
}


###
# Supprimer une tournée
DELETE http://localhost:4545/round/63e06275a8f1bf0305d86ba2 HTTP/1.1
Content-Type: application/json


###
# Affecter une tournée à un livreur à une date
POST http://localhost:4545/round/affect HTTP/1.1
Content-Type: application/json

{
  "id": "63e02b365a091bf6218e892a",
  "date": "12",
  "delivererid": "63e018295d1719e427da79d4"
}


###
# Récupération des tournées d'un livreur
GET http://localhost:4545/round?delivererid=63e01da4cf04b679ee43bbb2 HTTP/1.1
Content-Type: application/json
